mysite/mypolls/urls.py
from django.conf.urls import url, patterns

from mypolls import views

urlpatterns = patterns('',
            url(r'^$', views.index, name='index'),
            #url(r'^(?P<poll_id>\d+)/$',views.detail, name='detail'),
            url(r'^(?P<poll_id>\d+)/$',views.detail,name='detail'),
            url(r'^(?P<poll_id>\d+)/results/$', views.results,name='results'),
            url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

mysite/mysite/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^mypolls/', include('mypolls.urls', namespace="mypolls")),
    url(r'^admin/', include(admin.site.urls)),
)

mysite/polls/urls.py
#!/usr/bin/env python
from django.conf.urls import patterns, url
from polls import views

urlpatterns = patterns('',url(r'^$',views.index, name='index'),
                       url(r'^(?P<poll_id>\d+)/$',views.detail,name='detail'),
                       url(r'^(?P<poll_id>\d+)/results/$',views.results,name='results'),
                       url(r'^(?P<poll_id>\d+)/vote/$',views.vote,name='vote'),
                       )

mysite/mypolls/models.py
from django.db import models

from django.utils import timezone
import datetime

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.question
    
    def was_published_recently(self):
        return timezone.now()-datetime.timedelta(days=1)<=self.pub_date <timezone.now()
    
class Choice(models.Model):
    poll_id = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice_text
    

mysite/polls/models.py
from django.db import models
import datetime
from django.utils import timezone

class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __unicode__(self):
        return self.question
    
    def was_published_recently(self):
        now = timezone.now()
        return now-datetime.timedelta(days=1)<=self.pub_date <now
        
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published Recently?'
    
    def choice_count(self):
        return self.choice_set.count()
    
    choice_count.short_description = 'Choices'
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __unicode__(self):
        return self.choice_text

# Create your models here.

mysite/southtut/models.py
from django.db import models

# Create your models here.

mysite/mypolls/views.py
from django.http import HttpResponse, Http404, HttpResponseRedirect

from django.shortcuts import render, get_object_or_404, get_list_or_404

from django.core.urlresolvers import reverse

from mypolls.models import Poll, Choice

def index(request):
    poll_list = get_list_or_404(Poll)
    return render(request,'mypolls/index.html',{'poll_list':poll_list})
    
def detail(request,poll_id):
    poll = get_object_or_404(Poll,pk=poll_id)
    return render(request,'mypolls/detail.html',{'poll':poll})
    
    
def results(request,poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request,'mypolls/results.html',{'poll':poll})
    
def vote(request, poll_id):
    p = get_object_or_404(Poll,pk=poll_id)
    try:
        choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request,'mypolls/detail.html', {'poll':p,'error_message':'You have not selected a choice'})
        
    else:
        choice.votes +=1
        choice.save()
        return HttpResponseRedirect(reverse('mypolls:results',args=(p.id,)))
        
        
    

mysite/polls/views.py
# Create your views here.
from django.http import HttpResponse, HttpResponseRedirect
from django.http import Http404

from django.template import RequestContext, loader

from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.core.urlresolvers import reverse

from django.utils import timezone

from polls.models import Poll, Choice

def index(request):
    latest_poll_list = Poll.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
    output = ', '.join(p.question for p in latest_poll_list)
    #return HttpResponse(output)
    template = loader.get_template('polls/index.html')
    context = RequestContext(request,{'latest_poll_list': latest_poll_list, })
    return HttpResponse(template.render(context))
    
def detail(request,poll_id):
    try:
        poll = Poll.objects.get(pk=poll_id)
    except Poll.DoesNotExist:
        raise Http404
        
    return render(request,'polls/detail.html',{'poll':poll})
    
    

def results(request,poll_id):
    poll = get_object_or_404(Poll,pk=poll_id)
    return render(request,'polls/results.html',{'poll':poll})

def vote(request,poll_id):
    p = get_object_or_404(Poll,pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'poll':p, 'error_message':'You have not selected a choice'})
        
    else:
        selected_choice.votes+=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(p.id,)))
    

mysite/southtut/views.py
# Create your views here.

mysite/mypolls/templates/mypolls/detail.html
<H1>{{ poll.question }}</H1>
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}
<form action="{% url 'mypolls:vote' poll.id %}" method="post">
{% csrf_token %}
    {% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{forloop.counter}}"> {{ choice.choice_text }}</label> <br/>
    {% endfor %}
    
    <input type="submit" value="Vote" />
</form>

<a href="{% url 'mypolls:index'%}"> Back to My Polls</a>

mysite/mypolls/templates/mypolls/index.html
<!-- {% load staticfiles %}

 <link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" /> -->
{% if poll_list %}
    <ul>
    {% for poll in poll_list %}
        <li> <a href="{% url 'mypolls:detail' poll.id %}" >{{poll.question }}</a></li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No Polls available.</p>
    
{% endif %}

mysite/mypolls/templates/mypolls/results.html
<H1>{{ poll.question }}</H1>
<ul>
    {% for choice in poll.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}
</ul>

<a href="{% url 'mypolls:index' %}" >Back to My Polls?</a>

mysite/polls/templates/polls/detail.html
<H1>{{ poll.question }}</H1>
{% if error_message %}<p><strong>{{ error_message }} </strong></p>{% endif %}
<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
    {% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{forloop.counter}}"> {{ choice.choice_text }}</label> <br/>
    {% endfor %}
    
    <input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li> <a href="{% url 'polls:detail' poll.id %}" >{{poll.question }}</a></li>
    
    {% endfor %}
    </ul>
{% else %}
    <p>No Polls available.</p>
    
{% endif %}

mysite/polls/templates/polls/results.html
<H1>{{ poll.question }}</H1>
<ul>
    {% for choice in poll.choice_set.all %}
    <li>{{choice.choice_text}} -- {{choice.votes}} vote{{ choice.votes|pluralize }} </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}" >Vote Again?</a>